version: "3.7"

services:
  sg-ui:
    container_name: sg-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      BASE_USERS_API: http://localhost:8090/api/v1
      BASE_LOGIN_API: http://localhost:8080/api/v1
      BASE_MAILING_API: http://localhost:8081/api/v1/mailing
      BASE_REQUEST_API: http://localhost:9000/api/v1
      BASE_MANAGER_API: http://localhost:8088/api/v1
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
