version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mailing
    ports:
      - "8081:8080"
    depends_on:
      - mailhog
      - db
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: local_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${USERS_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./config/postgres-init:/docker-entrypoint-initdb.d
    networks:
      - app_network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    profiles:
      - local

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: "mailhog"
    environment:
      SMTP_HOST: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
    ports:
      - "${SMTP_PORT}:${SMTP_PORT}"
      - "${MH_WEB_UI_PORT}:${MH_WEB_UI_PORT}"
    restart: on-failure
    networks:
      - app_network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    profiles:
      - local

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
